name: "Goimports linter action"
description: "goimports check"
author: "xKamaiL"

inputs:
  local:
    description: "The local package name"
    required: true
    default: ""
  
outputs:
  goimports-output:
    description: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.local }}
